* Compactness, ultraproducts, Los's theorem and CL
\subsubsection{Compactness, ultraproducts and \cathoristic{}}

Mathematicals knows three substantially different approaches for
proving compactness: G\"odel's original approach, refined by Morley
and many others, uses proof rules and the completeness theorem.  Our
proof in Section \ref{compactnessProof} works by translation and
piggy-backs on the compactness of first-order logic. Finally, the
model-theoretic approach uses ultra-products as a tool for 'gluing'
together the models that guarantee finite
satisfiability. Ultra-products are quotients of reduced products by an
ultra-filter. The conditions defining ultra-filters are carefully
chosen to ensure that the quotient is indeed an appropriate model with
nice properties such as \L{}o\'{s}' theorem. In particular, for $U$ to
be an ultra-filter over some set $S$, for each $A \subseteq S$, either
$A$ or its complemnet $S\setminus A$ must be in $U$. This axiom
clearly reflects the semantics of negation. But \cathoristic{} doesn't
have negation. So what would an appropriate equivalent of
ultra-filters for \cathoristic{} look like that can be used to prove
compactness directly on models?
\richard{Do we need this?}
* Dualities 
\subsubsection{Extending \cathoristic{} with dualities}
In any modal logic with negation, the may modality and the must modality are interdefinable:
\[
\MUST{a}{\phi} = \neg
\MAY{a}{\neg \phi}
\]
In \cathoristic{}, the situation is different: since
negation is not available, adding $\MUST{a}{\phi}$ is a substantial
change to the logic.
For example, the processes in Figure
\ref{figure:counterexample}\richard{Which figure is this?}, indistinguishable by cathoristic formulae, are
separated by
  \[
     \MUST{a}{\MAY{b}{}},
  \]
  assuming the usual semantics: $(\LLL, s) \models \MUST{a}{\phi}$ if
  $s \TRANS{a} t$ implies that $(\LLL, t) \models \phi$. This means
  Theorem \ref{theorem:completeLattice} fails. What notion of model
  equivalence does elementary equivalence become in this scenario?
  What do complete proof rules look like?

  Similar questions can be asked for other additional primitives. If negation is 
  available, the formula
  \[
     \MAY{a}{\neg \MAY{b}{} }
  \]
  separates the afromentioned examples. If we add implication instead,
  negation becomes definable: $\neg \phi = \phi \rightarrow \bot$.
\richard{In one sense, adding the must modality is not further work. If we add negation, as in section 10, then we can define must modality in the obvious way. It is only further work if we add $\Box$ as a primitive without adding negation.}

* Extending CL with fixpoints a la modal mu calculus
\subsubsection{\Cathoristic{} as a fragment of first- and second-order logic }

A question that has been fruitful in modal logic has been which
fragment of first-order logic corresponds to modal formulae?  Van
Benthem established that modal logic is the fragment of first-order
logic invariant under bisimulation \cite{BlackburnP:modlog}. What is
the the fragment corresponding to \cathoristic{}? Our Theorem
\ref{theorem:completeLattice} suggests to look at closure under mutual
simulation.  

Van Benthem's result was generalised to monadic second
order by Janin and Walukiewicz \cite{JaninD:expcomotpmcwrtmsol} who
showed that the bisimulation invariant fragment of monadic
second-order logic is the modal $\mu$-calculus, an extension of modal
logic with fixpoint operators \cite{KozenD:respromc}.  It would be
interesting to study the \emph{cathoristic $\mu$-calculus}, which adds
fixpoints to \cathoristic{}:
\begin{GRAMMAR}
  \phi
     &::=&
  \TRUE
     \VERTICAL
  \phi \AND \psi
     \VERTICAL
  \MAY{a}\phi
     \VERTICAL
  !A
     \VERTICAL
  \mu \PVAR{x}.\phi
     \VERTICAL
  \nu \PVAR{x}.\phi
     \VERTICAL
  \PVAR{x}
\end{GRAMMAR}

\NI Here $\PVAR{x}$ ranges over propositional variables.  Such a logic
would be useful for talking about infinite transition systems and the
structures of exclusion they give rise to.  For example the phases of
a traffic light can be described as follows.
\[
   \MAY{tl}{\MAY{colour}{\mu \PVAR{x}.
       (!\{green\} \AND \MAY{green}{
         (!\{amber\} \AND \MAY{amber}{
           (!\{red\} \AND \MAY{red}{\PVAR{x}})})})}}
\]

 What properties does the
cathoristic $\mu$-calculus have? In the absence of negation, a lot of proof
techniques taken for granted in the meta-theory of the modal
$\mu$-calculus, such as the relationship between least and greatest
fixpoints, is no longer available.

* Build a programming language along the lines of Prolog,
i.e. study unification, resolution, machine-usable proofs
* Algebraic semantics, more generally Categorical semantics of CL?
* What kind of operator is Incomp(.)?
* Study CL as a database query language, query complexity?
* WHat exactly is the fragment of FOL corresponding to CL?
* What is the relationship between \bot in cut-elimination proofs, and Incomp(.)?
